sudo: required

language: go

go:
  - master

services:
  - docker

env:
  - FILEBEAT_VERSION=5.0.0

install:
  - curl -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-$FILEBEAT_VERSION-linux-x86_64.tar.gz
  - tar -xzf filebeat-$FILEBEAT_VERSION-linux-x86_64.tar.gz
  - mv filebeat-$FILEBEAT_VERSION-linux-x86_64/filebeat ./
  - docker build -t patrickeasters/filebeat-kubernetes-gelf .

after_success:
  - if [ "$TRAVIS_BRANCH" != "" ]; then
    docker tag patrickeasters/filebeat-kubernetes-gelf patrickeasters/filebeat-kubernetes-gelf:$TRAVIS_TAG;
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push patrickeasters/filebeat-kubernetes-gelf:$TRAVIS_TAG;
    docker push patrickeasters/filebeat-kubernetes-gelf:latest;
    fi
