filebeat.prospectors:
- input_type: log
  paths:
    - "/var/log/containers/*.log"
  document_type: kube-logs
  tail_files: true

output.logstash:
  hosts: [ $LOGSTASH_HOSTS ]
  timeout: 15

logging.level: ${LOG_LEVEL:error}
